/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedThesisRouteImport } from './routes/_authenticated/thesis'
import { Route as AuthenticatedSourcingRouteImport } from './routes/_authenticated/sourcing'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedFoundersRouteImport } from './routes/_authenticated/founders'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as AuthenticatedOpportunityIdRouteImport } from './routes/_authenticated/opportunity.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedThesisRoute = AuthenticatedThesisRouteImport.update({
  id: '/thesis',
  path: '/thesis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSourcingRoute = AuthenticatedSourcingRouteImport.update({
  id: '/sourcing',
  path: '/sourcing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFoundersRoute = AuthenticatedFoundersRouteImport.update({
  id: '/founders',
  path: '/founders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOpportunityIdRoute =
  AuthenticatedOpportunityIdRouteImport.update({
    id: '/opportunity/$id',
    path: '/opportunity/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/founders': typeof AuthenticatedFoundersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sourcing': typeof AuthenticatedSourcingRoute
  '/thesis': typeof AuthenticatedThesisRoute
  '/opportunity/$id': typeof AuthenticatedOpportunityIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/founders': typeof AuthenticatedFoundersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sourcing': typeof AuthenticatedSourcingRoute
  '/thesis': typeof AuthenticatedThesisRoute
  '/opportunity/$id': typeof AuthenticatedOpportunityIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/founders': typeof AuthenticatedFoundersRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/sourcing': typeof AuthenticatedSourcingRoute
  '/_authenticated/thesis': typeof AuthenticatedThesisRoute
  '/_authenticated/opportunity/$id': typeof AuthenticatedOpportunityIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/founders'
    | '/settings'
    | '/sourcing'
    | '/thesis'
    | '/opportunity/$id'
    | '/api/public/health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/founders'
    | '/settings'
    | '/sourcing'
    | '/thesis'
    | '/opportunity/$id'
    | '/api/public/health'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/founders'
    | '/_authenticated/settings'
    | '/_authenticated/sourcing'
    | '/_authenticated/thesis'
    | '/_authenticated/opportunity/$id'
    | '/api/public/health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/thesis': {
      id: '/_authenticated/thesis'
      path: '/thesis'
      fullPath: '/thesis'
      preLoaderRoute: typeof AuthenticatedThesisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sourcing': {
      id: '/_authenticated/sourcing'
      path: '/sourcing'
      fullPath: '/sourcing'
      preLoaderRoute: typeof AuthenticatedSourcingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/founders': {
      id: '/_authenticated/founders'
      path: '/founders'
      fullPath: '/founders'
      preLoaderRoute: typeof AuthenticatedFoundersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/opportunity/$id': {
      id: '/_authenticated/opportunity/$id'
      path: '/opportunity/$id'
      fullPath: '/opportunity/$id'
      preLoaderRoute: typeof AuthenticatedOpportunityIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFoundersRoute: typeof AuthenticatedFoundersRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSourcingRoute: typeof AuthenticatedSourcingRoute
  AuthenticatedThesisRoute: typeof AuthenticatedThesisRoute
  AuthenticatedOpportunityIdRoute: typeof AuthenticatedOpportunityIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFoundersRoute: AuthenticatedFoundersRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSourcingRoute: AuthenticatedSourcingRoute,
  AuthenticatedThesisRoute: AuthenticatedThesisRoute,
  AuthenticatedOpportunityIdRoute: AuthenticatedOpportunityIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
